### ISSUE TITLE
Constant configuration changes triggering Auto Configuration Backup

### ISSUE THREAD

**Issue by Napsterbater** [jmarchewka/apcupsd-pfsense-widget#1]
This widget seems to cause "configuration changes" with the reason "Save apcupsd apcaccess results" seemingly every time it is loaded or refreshed on the dashboard. 

This causes Auto Configuration Backup configured with "Automatically backup on every configuration change" to then backup the config every single time the widget is loaded or refreshed.

https://github.com/jmarchewka/apcupsd-pfsense-widget/blob/effc37b5ed0bc81d5a57135c7b98af3580cea6e9/apcupsd.widget.php#L40

**Comment by jmarchewka** [comment]
That's certainly not ideal. I fixed it with commit a0843b4.

**Comment by Napsterbater** [comment]
Looks to solve it, and the widget even loads faster. Win Win.
